version: 2
jobs:
  PIO:
    docker:
      - image: raspbian/stretch
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git python3 python3-pip python3-dev
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
            platformio platform install file://.
      - run:
          name: "Build"
          command: |
            platformio run -d examples/blink
      - run:
          name: "Test"
          command: |
            platformio run -d examples/wiringpi-serial
            platformio run -d examples/wiringpi-blink

workflows:
    version: 2
    run_ci:
        jobs:
            - PIO
